### ISSUE TITLE
Nice, +1

### ISSUE THREAD

**Issue by ahmogit** [poregan/compare-structures#1]
Tip o' the hat for writing this. It's a pleasure to have finally found a carefully written function that  performs this much-needed functionality **correctly**.  

There are a ton of cargo-cult attempts at this all over the place (Mathworks file exchange, stack exchange, etc.) but none actually worked properly for anything other than simple cases.  

Much appreciated. +1

**Comment by poregan** [comment]
Thank you for the kind words! Glad you've found it useful :)
